pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "python-flask-api:1.0"
        K8S_DEPLOYMENT = "deployment.yaml"
        K8S_SERVICE = "service.yaml"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/wajidiqbal787/Kubernetes-On-Minikube.git'
            }
        }

        stage('Setup Python & Install') {
            steps {
                sh 'python3 -m venv venv'
                sh 'source venv/bin/activate && pip install --upgrade pip'
                sh 'source venv/bin/activate && pip install -r Python-Flask-API/requirements.txt'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE Python-Flask-API'
            }
        }

        stage('Push Docker Image (Optional)') {
            steps {
                // Agar DockerHub use karna hai
                // sh 'docker tag $DOCKER_IMAGE yourdockerhubusername/$DOCKER_IMAGE'
                // sh 'docker push yourdockerhubusername/$DOCKER_IMAGE'
                echo 'Skipping push for local Minikube deployment'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                // Apply deployment & service
                sh 'kubectl apply -f Python-Flask-API/deployment.yaml'
                sh 'kubectl apply -f Python-Flask-API/service.yaml'
            }
        }

        stage('Check Deployment') {
            steps {
                sh 'kubectl get pods -o wide'
                sh 'kubectl get svc'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
    }
}
