pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build("php-hello-app:1.0")
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
