apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Pod container port
      nodePort: 32100   # NodePort


